SCHEMA.sql

create table public.contribucionesporcasa (
  id_casa bigint generated by default as identity not null,
  id_contribucion bigint not null,
  fecha_cargo date not null,
  estado text not null,
  monto_pagado double precision null,
  url_comprobante text null,
  fechapago date null,
  fecha_maxima_pago date null,
  constraint contribucionesporcasa_pkey primary key (id_casa, id_contribucion, fecha_cargo),
  constraint tmp_fk_casa foreign KEY (id_casa) references usuarios (id),
  constraint tmp_fk_contribucion foreign KEY (id_contribucion) references contribuciones (id_contribucion)
) TABLESPACE pg_default;


[
  {
    "id_casa": 5,
    "id_contribucion": 1,
    "fecha_cargo": "2026-01-28",
    "estado": "PAGADO",
    "monto_pagado": 14.19,
    "url_comprobante": "https://wtczfdkldixaptrskjwb.supabase.co/storage/v1/object/public/imagenespagos/pagos/1770628441384_d06ngdodfbv.jpeg",
    "fechapago": "2026-02-08",
    "fecha_maxima_pago": "2026-02-26"
  },
  {
    "id_casa": 6,
    "id_contribucion": 1,
    "fecha_cargo": "2026-02-28",
    "estado": "MOROSO",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-03-29"
  },
  {
    "id_casa": 7,
    "id_contribucion": 1,
    "fecha_cargo": "2026-03-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-04-26"
  },
  {
    "id_casa": 8,
    "id_contribucion": 1,
    "fecha_cargo": "2026-04-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-05-27"
  },
  {
    "id_casa": 9,
    "id_contribucion": 1,
    "fecha_cargo": "2026-05-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-06-26"
  },
  {
    "id_casa": 10,
    "id_contribucion": 1,
    "fecha_cargo": "2026-06-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-07-27"
  },
  {
    "id_casa": 11,
    "id_contribucion": 1,
    "fecha_cargo": "2026-07-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-08-26"
  },
  {
    "id_casa": 12,
    "id_contribucion": 1,
    "fecha_cargo": "2026-08-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-09-26"
  },
  {
    "id_casa": 1,
    "id_contribucion": 1,
    "fecha_cargo": "2026-09-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-10-27"
  },
  {
    "id_casa": 2,
    "id_contribucion": 1,
    "fecha_cargo": "2026-10-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-11-26"
  },
  {
    "id_casa": 5,
    "id_contribucion": 1,
    "fecha_cargo": "2026-11-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2026-12-27"
  },
  {
    "id_casa": 6,
    "id_contribucion": 1,
    "fecha_cargo": "2026-12-28",
    "estado": "PENDIENTE",
    "monto_pagado": null,
    "url_comprobante": null,
    "fechapago": null,
    "fecha_maxima_pago": "2027-01-26"
  }
]